# Generated by Django 4.1.2 on 2022-10-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hobby", "취미/교양"),
                            ("study", "스터디"),
                            ("daliy", "일상"),
                            ("exercise", "운동"),
                            ("etc", "기타"),
                        ],
                        default="카테고리1",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("howto", models.TextField()),
            ],
        ),
    ]
