# Generated by Django 4.0.4 on 2022-10-10 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0002_club_created_at_club_updated_at_club_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('user', models.ManyToManyField(blank=True, related_name='todo_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
