# Generated by Django 4.0.4 on 2022-10-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='box',
            field=models.BooleanField(default=False),
        ),
    ]
